name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        # Check https://github.com/dotnet/core/blob/master/release-notes/releases-index.json for updates
        dotnet:
          - "2.1.202" # Latest 2.0
          - "2.1.805" # Latest 2.1
          - "2.2.207" # Latest 2.2
          - "3.0.103" # Latest 3.0
          - "3.1.201" # Latest 3.1

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - uses: actions/checkout@master
